[tool.poetry]
name = "waka-readme"
version = "0.1.8"
description = "Wakatime Weekly Metrics on your Profile Readme."
authors = ["Athul Cyriac Ajay <athul8720@gmail.com>"]
license = "MIT"
readme = "README.md"
#packages = [{include = "waka_readme"}]

[tool.poetry.dependencies]
python = "^3.11"
faker = "^16.7.0"
requests = "^2.28.2"
pygithub = "^1.57"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"
pylint = "^2.16.1"
python-dotenv = "^0.21.1"
loguru = "^0.6.0"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
